import React from 'react';
import { Link } from 'react-router-dom';

const Disclaimer = () => {
    return (
        <div style={{ maxWidth: '900px', margin: '0 auto', padding: '60px 40px', color: '#ececf1', fontFamily: 'Inter, sans-serif', lineHeight: '1.7' }}>
            <h1 style={{ fontSize: '2.5rem', marginBottom: '1rem', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Disclaimer</h1>
            <p style={{ color: 'rgba(255, 255, 255, 0.6)', marginBottom: '2rem' }}>Last updated: {new Date().toLocaleDateString()}</p>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>1. General Information</h2>
                <p>The information provided by Tipde AI ("we," "us," or "our") on tipde.top (the "Site") and through our AI chatbot service is for general informational purposes only. All information is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site or generated by our AI.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>2. Artificial Intelligence (AI) Disclaimer</h2>
                <p><strong>IMPORTANT:</strong> This website utilizes Artificial Intelligence technology to generate responses and content. While we strive for accuracy and helpfulness, AI-generated content can occasionally be:</p>
                <ul style={{ paddingLeft: '1.5rem', marginTop: '1rem' }}>
                    <li style={{ marginBottom: '0.75rem' }}>Incorrect or inaccurate</li>
                    <li style={{ marginBottom: '0.75rem' }}>Misleading or incomplete</li>
                    <li style={{ marginBottom: '0.75rem' }}>Out of date or outdated</li>
                    <li style={{ marginBottom: '0.75rem' }}>Biased or contain errors</li>
                </ul>
                <p style={{ marginTop: '1rem' }}><strong>You should NOT rely solely on AI-generated information for:</strong></p>
                <ul style={{ paddingLeft: '1.5rem', marginTop: '1rem' }}>
                    <li style={{ marginBottom: '0.75rem' }}>Medical advice or health decisions</li>
                    <li style={{ marginBottom: '0.75rem' }}>Legal advice or legal matters</li>
                    <li style={{ marginBottom: '0.75rem' }}>Financial advice or investment decisions</li>
                    <li style={{ marginBottom: '0.75rem' }}>Professional consulting in any field</li>
                    <li style={{ marginBottom: '0.75rem' }}>Emergency or crisis situations</li>
                </ul>
                <p style={{ marginTop: '1rem' }}>Always verify important information with qualified professionals in the relevant field.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>3. No Professional Advice</h2>
                <p>The Site and our AI service cannot and do not provide professional advice. The information is provided for general informational and educational purposes only and is not a substitute for professional advice.</p>
                <p style={{ marginTop: '1rem' }}>Accordingly, before taking any actions based upon information provided by our AI or on our website, we strongly encourage you to consult with appropriate licensed professionals, including but not limited to:</p>
                <ul style={{ paddingLeft: '1.5rem', marginTop: '1rem' }}>
                    <li style={{ marginBottom: '0.75rem' }}>Medical professionals for health-related questions</li>
                    <li style={{ marginBottom: '0.75rem' }}>Licensed attorneys for legal matters</li>
                    <li style={{ marginBottom: '0.75rem' }}>Financial advisors for investment decisions</li>
                    <li style={{ marginBottom: '0.75rem' }}>Tax professionals for tax advice</li>
                </ul>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>4. External Links Disclaimer</h2>
                <p>The Site may contain links to external websites, third-party content, or advertisements (including Google AdSense). Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.</p>
                <p style={{ marginTop: '1rem' }}>WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE OR ANY WEBSITE OR FEATURE LINKED IN ANY BANNER OR OTHER ADVERTISING.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>5. Advertising Disclaimer</h2>
                <p>This website uses Google AdSense to display advertisements. These ads are served by Google and may be based on your browsing history and interests. We do not have control over the content of these advertisements.</p>
                <p style={{ marginTop: '1rem' }}>The presence of an advertisement on our website does not constitute an endorsement of the advertised product, service, or company.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>6. Limitation of Liability</h2>
                <p>IN NO EVENT SHALL TIPDE AI, NOR ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES, BE LIABLE FOR:</p>
                <ul style={{ paddingLeft: '1.5rem', marginTop: '1rem' }}>
                    <li style={{ marginBottom: '0.75rem' }}>Any indirect, incidental, special, consequential, or punitive damages</li>
                    <li style={{ marginBottom: '0.75rem' }}>Loss of profits, data, use, goodwill, or other intangible losses</li>
                    <li style={{ marginBottom: '0.75rem' }}>Damages resulting from your access to or use of (or inability to access or use) the Service</li>
                    <li style={{ marginBottom: '0.75rem' }}>Any conduct or content of any third party on the Service</li>
                    <li style={{ marginBottom: '0.75rem' }}>Any content obtained from the Service</li>
                    <li style={{ marginBottom: '0.75rem' }}>Unauthorized access, use, or alteration of your transmissions or content</li>
                </ul>
                <p style={{ marginTop: '1rem' }}>This applies whether based on warranty, contract, tort (including negligence), or any other legal theory, whether or not we have been informed of the possibility of such damage.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>7. Use at Your Own Risk</h2>
                <p>YOUR USE OF THE SERVICE, ITS CONTENT, AND ANY AI-GENERATED RESPONSES ARE AT YOUR SOLE RISK. The Service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>8. Fair Use Disclaimer</h2>
                <p>This site may contain copyrighted material the use of which has not always been specifically authorized by the copyright owner. We make such material available in an effort to provide educational and informational content. We believe this constitutes a "fair use" of any such copyrighted material as provided for in section 107 of the US Copyright Law.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>9. Changes to This Disclaimer</h2>
                <p>We reserve the right to make changes to this Disclaimer at any time. Your continued use of the Service following the posting of changes constitutes your acceptance of such changes.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontSize: '1.75rem', marginBottom: '1rem', color: '#fff' }}>10. Contact Information</h2>
                <p>If you have any questions about this Disclaimer, please contact us through our <Link to="/contact" style={{ color: '#667eea', textDecoration: 'underline' }}>Contact page</Link>.</p>
            </section>

            <div style={{ marginTop: '3rem', padding: '1.5rem', background: 'rgba(255, 193, 7, 0.1)', borderLeft: '4px solid #ffc107', borderRadius: '8px' }}>
                <p style={{ margin: 0, fontSize: '0.95rem' }}><strong>⚠️ IMPORTANT:</strong> This disclaimer is subject to change without notice. Please review it periodically. By using our service, you acknowledge that you have read, understood, and agree to be bound by this Disclaimer.</p>
            </div>

            <div style={{ marginTop: '2rem', textAlign: 'center' }}>
                <Link to="/" style={{ color: '#667eea', textDecoration: 'none', fontSize: '1rem' }}>← Back to Home</Link>
            </div>
        </div>
    );
};

export default Disclaimer;
